<template>
  <div class="page-header">
    <div class="ui container secondary massive stackable menu">
      <nuxt-link to="/">
        <div class="ui item">
          <i class="bullseye icon big" />
          <div class="content">
            <h1 class="ui header">Eventrul</h1>
          </div>
        </div>
      </nuxt-link>
      <div class="right menu">
        <a class="item">
          Teenusepakkujale
        </a>
        <a class="item">
          Kontakt
        </a>
        <div class="item">
          <button class="ui button small primary">
            LOGI SISSE
          </button>
        </div>
      </div>
    </div>

    <div class="ui container">
      <div class="ui card cta">
        <div class="content">
          <div class="ui items">
            <div class="item">
              <div class="content">
                <div class="ui header huge">
                  Tahad korraldada ägeda ürituse?
                </div>
              </div>
            </div>
            <div class="item">
              <div class="content">
                <h4 class="ui header">MILLAL?</h4>
                <div class="ui calendar" id="date_calendar">
                  <div class="ui input left icon fluid large">
                    <i class="calendar icon"></i>
                    <input type="text" placeholder="Kuupäev" />
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="content">
                <h4 class="ui header">KUS?</h4>
                <div class="ui fluid left icon input large">
                  <input type="text" placeholder="Asukoht" />
                  <i class="map marker icon"></i>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="content">
                <h4 class="ui header">MITMEKESI?</h4>
                <div class="ui fluid left icon input large">
                  <input type="text" placeholder="Inimeste arv" />
                  <i class="users icon"></i>
                </div>
              </div>
            </div>
            <div class="item">
              <button class="ui button secondary right floated fluid">
                OTSI
              </button>
            </div>
          </div>
        </div>
      </div>
      <i
        class="angle double down huge inverted icon slide-top"
        style="position: absolute; left: 0; right: 0; margin: auto; bottom: 1%; cursor: pointer"
        v-scroll-to="'#FpScrollTarget'"
      ></i>
    </div>
  </div>
</template>

<script>
export default {
  name: 'frontPageHeader',
  data() {
    return {}
  },
  mounted() {
    // eslint-disable-next-line
    $('#date_calendar').calendar()
  }
}
</script>

<style lang="scss" scoped>
.page-header {
  height: 100vh;
  position: relative;
  padding-top: 1rem;

  background: url('~assets/images/fp-header-image.jpg');
  background-position-x: left;
  background-position-y: center;
  background-size: cover;

  .cta {
    width: 600px;
  }

  .items {
    .item {
      padding-top: 0.75rem;
      padding-bottom: 0.75rem;
    }
  }

  .title {
    color: white;
    font-size: 7rem;
    font-weight: 900;
  }

  .subtitle {
    color: white;
    font-size: 5rem;
    font-weight: 500;
    position: absolute;
    bottom: 5rem;
  }
}

.slide-top {
  -webkit-animation: slide-top 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    infinite alternate both;
  animation: slide-top 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) infinite
    alternate both;

  @media only screen and (max-width: 768px) {
    display: none;
  }
}

/* ----------------------------------------------
* Generated by Animista on 2019-6-13 19:41:46
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}
</style>
